kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: agnewp
    password:
      from_secret: dh_password
    repo: agnewp/locust
    tags: 
     - latest
     - 0.9.0
    
