kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username: agnewp@gmail.com
    password:
      from_secret: docker_password
    repo: agnewp/locust
    tags: 
     - latest
     - 0.9.0
    
