kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: username
    password:
      from_secret: password
    repo: agnewp/locust
    tags: 
     - latest
     - 0.9.0
    
